server:
  port: 7999
spring:
  servlet:
    multipart:
      max-file-size: 20MB #限制文件上传的大小
      location: /data/upload_tmp
  datasource:
    url: jdbc:mysql://${tourguide.datasourceServer}:3306/tour_guide_applet?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '053073@Zd'
  jackson:
  #    default-property-inclusion: non_null
  redis:
    jedis:
      pool:
        max-active: 100
        max-idle: 10
    host: ${tourguide.myServer}
    port: 6379
    password: '053073@Zd'
  rabbitmq:
    host: ${tourguide.myServer}
    username: fengenchun
    password: 'fengenchun'
    virtual-host: /
    port: 5672
mybatis:
  type-aliases-package: com.guide.user.pojo
wechat:
  url: 'https://api.weixin.qq.com/sns/jscode2session'
  granttype: 'authorization_code'
  appid: 'wx4647cdec89c56e4c'
  secret: '70ec390fe9e9725372f04d188e17decb'
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - ${tourguide.myServer}:22122
tourguide:
  datasourceServer: localhost
  myServer: 1.15.103.43
  upload:
    base_url: https://www.tianyaguet.club/
    imageAllowTypes:
      - image/jpeg
      - image/png
      - image/bmp
  sms:
    effectiveTime: "5"        #短信有效时间（单位：分钟）
    codeTemplateId: 431479    #短信签名模板
    appid: 1400486555         #应用id
    appkey: 3f7d283fe2e1501038c4a1ce4ddedfcf
    smsSign: "冯恩春的毕设"
    nationCode: "86"
  mailbox:
    effectiveTime: "5"
    authCode: sjitgecsrmxqbghi
    emailSender: 308501273@qq.com